### ISSUE TITLE
Where is the weights.h5 file?

### ISSUE THREAD

**Issue by vmohana** [Gurupradeep/FCN-for-Semantic-Segmentation#2]
I tried running your code but I always come across an error that says weights.h5 cannot be found. I downloaded another weights file, but using that shows another error saying "you are trying to load a 0 layer model into a 19 layer model". Upon further digging I found out that this has something to do with the version of keras being used.

So my questions are:
1. Where is the weights.h5 file?
2. If I can't get that file, what is the version of keras you used to build this project?

Thank you

**Comment by Gurupradeep** [comment]
I used Keras 2 for this project. And regarding weights i will add the drive link to the weights file in sometime.

**Comment by vmohana** [comment]
Thank you so much

**Comment by vmohana** [comment]
Hey,
Sorry to bother, but is it possible for you to upload the weights file soon?
